# TLS-Certs
crtpath: /path/to/cert.crt
keypath: /path/to/cert.key

# HTTP-Basic-Auth-Credentials (in hashed form, see htpasswd)
# defaulting to "prometheus" & "hello" here
authuser: "prometheus"
authpass: "$apr1$Q9DfPfFo$xxVkL02CMMonCEERocsEp0"

# port and endpoint for http-endpoint
httpport: 8080
httpendpoint: '/metrics'

# time between two monitoring-attempts
monitoringinterval: 10m

# Time between server-setup-startups
# this is to avoid doing everything at once, even while it is all concurrent
startupoffset: 15s

# Time until mail must have arrived after sending for positive outcome
mailchecktimeout: 3m


servers:
    - name: localhost                     # name for internal prometheus-metric
      server: localhost                   # SMTP-server to use
      port: 587                           # port to use on Server for SMTP
      login: monitoring                   # login on server
      passphrase: 123password             # SMTP-login-password
      from: monitoring@helper1.com        # From-Header of monitoring-Mail (e.g. for filtering)
      to: monitoring@example.com          # address to deliver to
      detectiondir: /home/me/Maildir/new  # Maildir in which to look for monitoring-mail
    - name: helper1
      server: mail.helper1.org
      port: 587
      login: monitoring@helper1.org
      passphrase: password123
      from: monitoring@helper1.org
      to: monitoring@example.com
      detectiondir: /home/me/Maildir/new
